### ISSUE TITLE
I cannot successfully upload a .csv with columns fname, lname, note

### ISSUE THREAD

**Issue by richard-herron** [charwick/pick.al#1]
First, thanks for pick.al! I have a CSV of students with columns first name, last name, and note. But every time I upload, I get a "This file isn't a CSV!" error. Here is what my CSV looks like:

```
fname,lname,note
Gene,Fama,2
Ken,French,2
```

I have tried with and without quotes on strings, but I still get the "This file isn't a CSV!" error. My course CSV has 104 entries, so I prefer not to enter them manually. Here is my [course URL on pick.al](https://pick.al/admin/class.php?class=32). Thanks!

**Comment by charwick** [comment]
Thanks for letting me know! That error gets thrown when the browser checks the MIME type of the uploaded file, so it's not even getting to the parsing step – apparently it thinks it's some other sort of file.

What's the filename you're using, and does it have a .csv extension? If so, could you also tell me your system and browser? I'll see if I can make that check a little more lenient.

**Comment by charwick** [comment]
Actually, even better: could you upload your CSV to the box under "Result" on this webpage and let me know what it says the MIME type is? https://developer.mozilla.org/en-US/docs/Web/API/File/type

**Comment by richard-herron** [comment]
Thanks! The file is a CSV with a .csv extension on Windows 10 using Firefox 118.0.1.

I just successfully uploaded/parsed my 104-row CSV from Microsoft Edge.

So, the error was between my chair and my keyboard. Thanks for the quick response!

**Comment by richard-herron** [comment]
On Firefox, Both my toy and 104-row CSVs have MIME types: `students.csv: application/vnd.ms-excel`

On Edge, they have MIME types: `students.csv: text/csv`

**Comment by charwick** [comment]
Huh, apparently it's not distinguishing XLS and CSV files at all.
Closing this with https://github.com/charwick/pick.al/commit/38a7c8bbe3ecaefc2c9e9ccc4ad71f471a1ef477 – should work in Firefox now if you force refresh. Thanks again for noticing that.
